/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1536px",
      },

    },
    extend: {
      boxShadow:{
        '4xl': '0.1px 5px 1px 0px rgba(221, 128, 15, 1)',
      },
      spacing: {
        0.12: "0.125rem",
        0.25: "0.25rem",
        0.32: "0.32rem",
        0.38:"0.38rem",
        0.40: "0.40rem",
        0.5: "0.5rem",
        0.62: "0.62rem",
        0.68: "0.68rem",
        0.75: "0.75rem",
        0.9: "0.9rem",
        "1.0": "1rem",
        1.12: "1.125rem",
        1.25: "1.25rem",
        1.5: "1.5rem",
        1.75: "1.75rem",
        "2.0": "2rem",
        2.25: "2.25rem",
        2.5: "2.5rem",
        2.75: "2.75rem",
        "3.0": "3.0rem",
        3.5: "3.5rem",
        "4.0": "4.0rem",
        "5.0": "5rem",
        "5.5": "5.75rem",
        "6.0": "6rem",
        "7.0": "7rem",
        "8.0": "8rem",
        "9.0": "9rem",
        "10.0": "10rem",
        "12.0": "12rem",
        "13.0": "13rem",
        "15.0": "15rem",
        "16.0": "16rem",
        "18.0": "18rem",
        "20.0": "20rem",
        "22.0": "22rem",
        "24.0": "24rem",
        "25.0": "25rem",
        "26.0": "26rem",
        "28.0": "28rem",
        "29.0": "29rem",
        "30.0": "30rem",
        "32.0": "32rem",
        "35.0": "35rem",
        "36.0": "36rem",
        "37.0": "37rem",
        "38.0": "38rem",
        "40.0": "40rem",
        41.75: "41.75rem",
        "44.0": "44rem",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}