import AdminLayout from "@/layout/AdminLayout";
import { Divide } from "lucide-react";

export const metadata = {
  title: "Admin DashBoard",
  description: "Generated by create next app",
};
export default function AdminDashboardLayout({ children }) {
  return (
    <div className="">
      <AdminLayout child={children} />
    </div>
  );
}
